### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by argon1025** [argon1025/Harmony-serverless-backend#28]
AWS Lambda has been blocked by CORS policy: Request header field
해결

**Comment by argon1025** [comment]
serverless.yml cors: true를 아래와 같이 교체
추후 헤더에 사용자 정의 정보를 클라이언트로 부터 받을경우 헤더에 변수명 추가 필요
```
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
```

Response.js 에 아래 내용 추가
```
headers: {
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Credentials": true,
            },
```
